#### 전처리

In [72]:
# 가격 날짜 2023년으로 되어있어 해당년도 년으로 변경필요
# 가격 4년단위로 날짜 2/29인 이상 데이터 있는것들 제거필요. (2012년, 2016년)
# 날씨 시작부분에 있는 기간별조회 라는 필요없는 데이터 삭제
# 가격,날씨 확장자가 xls 이므로 xlsx 로 변환 필요


import numpy as np
import pandas as pd
import glob
import datetime as dt


def Prepro(name, start_year, end_year):
    
    # 가격 엑셀 불러오기
    df_prices = []  # 불러온 엑셀 파일들을 저장할 리스트

    for number in range(start_year, end_year + 1):
        file_name = f"./{name}/{name}가격{number}.xlsx"
        df_price = pd.read_excel(file_name, index_col='구분')
        df_prices.append(df_price)
        
    # 가격 행열 전치
    for i in range((end_year - start_year)+1):
        df_prices[i] = df_prices[i].T
    
    # 가격 연도 전부 합치기
    df_price_total = pd.concat(df_prices)
    
    df_price = df_price_total[['평균']]
    
    
    # ,제거 함수
    def remove_comma(x):
        if isinstance(x, str):
            return int(x.replace(',', ''))
        else:
            return x
    
    # ,제거
    df_price['평균'] = df_price['평균'].apply(remove_comma)


    # 증감치 컬럼 추가
#     df_price['증감치'] = df_price['평균'].diff()  
    
    
    
    
    # 날씨 엑셀 불러오기
    df_weathers = []

    for number in range(start_year, end_year+1):
        file_name = f"./{name}/{name}날씨{number}.xlsx"
        df_weather = pd.read_excel(file_name, index_col = '날짜')
        df_weathers.append(df_weather)
    
    # 날씨 처음 4개 행 제거
    for i in range((end_year - start_year)+1):
        df_weathers[i] = df_weathers[i].iloc[5:]
        
    # 날씨 연도 전부 합치기
    df_weather_total = pd.concat(df_weathers)
    df_weather = df_weather_total[['최고기온','최저기온','강수량']]
    
    # 강수량 - => 0
    df_weather.replace("-", 0, inplace=True)
    # 강수량 int 타입으로 변경
    df_weather['강수량'].astype(int)
    
    # 날씨 index(날짜)의 datetype이 달라 머신러닝을 위한 datetime으로 변경
    df_weather.index = pd.to_datetime(df_weather.index)
 
    df_weather = df_weather.drop('강수량', axis=1)
    
    # 가격에는 빈 날짜가 존재하여 날씨를 기준으로 합치기
    df = pd.concat([df_weather, df_price], axis=1)
    
    df = df.rename(columns={'평균':'가격'})
    
    df.reset_index(inplace=True)
    df.rename(columns={'index': '날짜'}, inplace=True)
    
    # 날짜를 월, 일, 연도로 분리하여 새로운 컬럼으로 추가
    df['월'] = df['날짜'].dt.month
    df['일'] = df['날짜'].dt.day
    df['연도'] = df['날짜'].dt.year    
    
    df.set_index('날짜', inplace=True)
   
    # 증감치 컬럼 추가
#     df['증감치'] = df['가격'].diff()
   
    df['가격2'] = df['가격']
    df = df.drop('가격', axis=1)
    df.rename(columns={'가격2': '가격'}, inplace=True)


    # Nan값 drop
    df = df.dropna()
    
    df.to_csv(f'{name}.csv', index_label='날짜')
    
    return df

In [110]:
Prepro('홍고추', 2011, 2022)

/var/folders/bl/gtwvyj550m31kshbvcc9vnpm0000gn/T/ipykernel_1707/2084058036.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_price['평균'] = df_price['평균'].apply(remove_comma)
/var/folders/bl/gtwvyj550m31kshbvcc9vnpm0000gn/T/ipykernel_1707/2084058036.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather.replace("-", 0, inplace=True)

            최고기온  최저기온   월   일    연도       가격
날짜
2011-01-03   1.6 -16.6   1   3  2011   4340.0
2011-01-04   0.3 -14.4   1   4  2011   4540.0
2011-01-05  -0.3  -6.5   1   5  2011   5060.0
2011-01-06  -2.6 -17.1   1   6  2011   5160.0
2011-01-07  -3.2 -18.7   1   7  2011   5040.0
...          ...   ...  ..  ..   ...      ...
2022-12-26  -2.2 -15.4  12  26  2022  11580.0
2022-12-27   0.7 -13.9  12  27  2022  11200.0
2022-12-28   0.5 -13.8  12  28  2022  11280.0
2022-12-29   1.3 -16.3  12  29  2022  10520.0
2022-12-30   1.7 -12.0  12  30  2022  10820.0

[2955 rows x 6 columns]

#### 머신러닝

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor

def machine(name):
    # csv 불러오기
    df = pd.read_csv(f'{name}.csv', index_col='날짜')

    X = df.loc[:, '최고기온':'연도']
    y = df['가격']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                  test_size=0.25)
    
    m1 = DecisionTreeRegressor()
    m2 = RandomForestRegressor()
    m3 = ExtraTreesRegressor()
    
    m1.fit(X_train, y_train)
    m2.fit(X_train, y_train)
    m3.fit(X_train, y_train)
    
    print(m1.score(X_test, y_test), m2.score(X_test, y_test), m3.score(X_test, y_test))
    
    return df

In [4]:
machine('감자')

0.9228774948077152 0.9486490348724884 0.975881732898512

            최고기온  최저기온   월   일    연도      가격
날짜
2011-01-03   6.2 -16.9   1   3  2011  1520.0
2011-01-04   3.2 -14.4   1   4  2011  1520.0
2011-01-05   2.9 -12.5   1   5  2011  1620.0
2011-01-06  -0.3 -18.1   1   6  2011  1690.0
2011-01-07   0.0 -20.7   1   7  2011  1710.0
...          ...   ...  ..  ..   ...     ...
2022-12-26  -0.5 -16.9  12  26  2022  2236.0
2022-12-27   1.0 -16.8  12  27  2022  2212.0
2022-12-28   0.4 -14.0  12  28  2022  2153.0
2022-12-29   0.0 -16.2  12  29  2022  2163.0
2022-12-30   2.3 -11.7  12  30  2022  2163.0

[2955 rows x 6 columns]

In [ ]:
앙상블, 부스팅, tx? xgb
라이브러리
서치관련 알고리즘 => 자동화

mysql

nodejs
mongoDB => nosql

orm 테이블 설계, 스키마

루트민스퀘어 오차가 얼마다

적용한 모델의 mse 의 수치가 얼마다

평균제곱오차(MSE), R2 score(R-squared)
> 회귀 평가 지표
원,


기획 배경 - 아이디어 이유 
개발 목표 - 
개발 내용 - 
머신러닝
 - 분석목표(농작물 예측)
 - 수집한 데이터
 - 데이터 전처리
 - 사용한 모델
 - 모델의 결과(평가, 예측)

In [ ]:
# React
component 중심 개발 -> 재사용

#### 머신 예측값

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor

def machine_p(name, HT, LT, month, day, year):
    # csv 불러오기
    df = pd.read_csv(f'{name}.csv', index_col='날짜')

    X = df.loc[:, '최고기온':'연도']
    y = df['가격']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                  test_size=0.25)
    
    m1 = DecisionTreeRegressor()
    m2 = RandomForestRegressor()
    m3 = ExtraTreesRegressor()
    
    m1.fit(X_train, y_train)
    m2.fit(X_train, y_train)
    m3.fit(X_train, y_train)
    
    print(m1.score(X_test, y_test), m2.score(X_test, y_test), m3.score(X_test, y_test))
    
    print(m1.predict([[HT, LT, month, day, year]]))
    print(m2.predict([[HT, LT, month, day, year]]))
    print(m3.predict([[HT, LT, month, day, year]]))

In [7]:
machine_p('감자',32.2,25.2,7,26,2023)

0.9071910180918257 0.953799048075566 0.9757951818787916
[1792.]
[1808.4]
[1816.49]

/Users/c/anaconda3/envs/machine/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
/Users/c/anaconda3/envs/machine/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/Users/c/anaconda3/envs/machine/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  warnings.warn(

#### R2, mse, rmse

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.metrics import mean_squared_error, r2_score

def machine(name):
    # csv 불러오기
    df = pd.read_csv(f'{name}.csv', index_col='날짜')

    X = df.loc[:, '최고기온':'연도']
    y = df['가격']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                  test_size=0.25)
    
    m1 = DecisionTreeRegressor()
    m2 = RandomForestRegressor()
    m3 = ExtraTreesRegressor()
    
    m1.fit(X_train, y_train)
    m2.fit(X_train, y_train)
    m3.fit(X_train, y_train)
    
    y_pred_m1 = m1.predict(X_test)
    y_pred_m2 = m2.predict(X_test)
    y_pred_m3 = m3.predict(X_test)
    
    mse_m1 = mean_squared_error(y_test, y_pred_m1)
    mse_m2 = mean_squared_error(y_test, y_pred_m2)
    mse_m3 = mean_squared_error(y_test, y_pred_m3)
    
    r2_m1 = r2_score(y_test, y_pred_m1)
    r2_m2 = r2_score(y_test, y_pred_m2)
    r2_m3 = r2_score(y_test, y_pred_m3)

    rmse_m1 = np.sqrt(mse_m1)
    rmse_m2 = np.sqrt(mse_m2)
    rmse_m3 = np.sqrt(mse_m3)
    
    print(f"Decision Tree R2 Score: {r2_m1}")
    print(f"Random Forest R2 Score: {r2_m2}")
    print(f"Extra Trees R2 Score: {r2_m3}")
    
    print(f"Decision Tree MSE: {mse_m1}")
    print(f"Random Forest MSE: {mse_m2}")
    print(f"Extra Trees MSE: {mse_m3}")
    
    print(f"Decision Tree RMSE: {rmse_m1}")
    print(f"Random Forest RMSE: {rmse_m2}")
    print(f"Extra Trees RMSE: {rmse_m3}")
    
    return df

In [31]:
machine('홍고추')

Decision Tree R2 Score: 0.7218272078857446
Random Forest R2 Score: 0.8082980419447056
Extra Trees R2 Score: 0.8731277180481529
Decision Tree MSE: 3572348.6346414075
Random Forest MSE: 2461873.5100290934
Extra Trees MSE: 1629318.3088098785
Decision Tree RMSE: 1890.065775215616
Random Forest RMSE: 1569.0358536467843
Extra Trees RMSE: 1276.4475346875322

            최고기온  최저기온   월   일    연도       가격
날짜
2011-01-03   1.6 -16.6   1   3  2011   4340.0
2011-01-04   0.3 -14.4   1   4  2011   4540.0
2011-01-05  -0.3  -6.5   1   5  2011   5060.0
2011-01-06  -2.6 -17.1   1   6  2011   5160.0
2011-01-07  -3.2 -18.7   1   7  2011   5040.0
...          ...   ...  ..  ..   ...      ...
2022-12-26  -2.2 -15.4  12  26  2022  11580.0
2022-12-27   0.7 -13.9  12  27  2022  11200.0
2022-12-28   0.5 -13.8  12  28  2022  11280.0
2022-12-29   1.3 -16.3  12  29  2022  10520.0
2022-12-30   1.7 -12.0  12  30  2022  10820.0

[2955 rows x 6 columns]